<template>

  <!--<div class="blog-text">-->
    <!--<p style="margin: 20px 0px 0px; padding: 0px; -webkit-tap-highlight-color: rgba(200, 200, 200, 0); color: #333333; font-family: 微软雅黑, 'Microsoft YaHei'; font-size: 16px;">随着《延禧攻略》与《如懿传》的播出，人们对乾隆皇帝后宫的关注再掀高潮。无论是&ldquo;喜塔腊&middot;尔晴&rdquo;的作妖必死，还是乾隆皇帝的&ldquo;大猪蹄子&rdquo;太花心，亦或是高贵妃&ldquo;本宫手都要抄断了&rdquo;的抄经吐槽。这些经典追剧梗都成为了时下人们茶余饭后的谈资。以至于这一个月来，故宫博物院里偏居一隅的延禧宫，竟成为了游客们参观打卡的重点。</p>-->
    <!--<p style="margin: 20px 0px 0px; padding: 0px; -webkit-tap-highlight-color: rgba(200, 200, 200, 0); color: #333333; font-family: 微软雅黑, 'Microsoft YaHei'; font-size: 16px;"><img style="color: transparent; font-size: 0px; vertical-align: middle; border: 0px; display: block; width: 910px; max-width: 100%; height: auto; margin-top: 15px; border-radius: 4px;" src="http://img1.lotour.net/Inspiration/2018/0911/20180911092906568982090_910.jpg" alt="" /></p>-->
    <!--<p style="margin: 20px 0px 0px; padding: 0px; -webkit-tap-highlight-color: rgba(200, 200, 200, 0); color: #333333; font-family: 微软雅黑, 'Microsoft YaHei'; font-size: 16px;"><img style="color: transparent; font-size: 0px; vertical-align: middle; border: 0px; display: block; width: 910px; max-width: 100%; height: auto; margin-top: 15px; border-radius: 4px;" src="http://img1.lotour.net/Inspiration/2018/0911/20180911092903339893430_910.jpg" alt="" /></p>-->
    <!--<p style="margin: 20px 0px 0px; padding: 0px; -webkit-tap-highlight-color: rgba(200, 200, 200, 0); color: #333333; font-family: 微软雅黑, 'Microsoft YaHei'; font-size: 16px;">其实在清代真实的宫廷生活里，嫔妃之间大多和睦相处，并没有影视剧中那样狗血的争斗。即便有个别现象，也会被给予严厉惩戒。乾隆皇帝的惇妃，就是那个最得乾隆皇帝喜爱，下嫁给丰绅殷德的十公主的母亲。她生性暴戾乖张，曾对宫女太监苛责动刑，以至于闹出人命。即便她深得圣宠，被乾隆皇帝知晓后，也受到降低品阶与高额罚款的双重制裁。更是在史书上遭到点名批评。看来，所谓的宫斗剧不过是好事者为迎合观众口味而编排的闹剧而已。什么戕害皇嗣，诬陷私通之类的套路，实在是经不起认真追究的。</p>-->
    <!--<h2 style="margin: 35px 0px 18px; padding: 0px 0px 0px 12px; -webkit-tap-highlight-color: rgba(200, 200, 200, 0); font-size: 16px; background-image: url('http://img1.lotour.net/i-article/txt-tit.png'); background-position: 0px center; background-size: initial; background-repeat: no-repeat; background-attachment: initial; background-origin: initial; background-clip: initial; color: #333333; font-family: 微软雅黑, 'Microsoft YaHei';">守护妻妾的乾隆皇帝</h2>-->
    <!--<p style="margin: 20px 0px 0px; padding: 0px; -webkit-tap-highlight-color: rgba(200, 200, 200, 0); color: #333333; font-family: 微软雅黑, 'Microsoft YaHei'; font-size: 16px;"><img style="color: transparent; font-size: 0px; vertical-align: middle; border: 0px; display: block; width: 910px; max-width: 100%; height: auto; margin-top: 15px; border-radius: 4px;" src="http://img1.lotour.net/Inspiration/2018/0911/20180911092859790160273_910.jpg" alt="" /></p>-->
    <!--<p style="margin: 20px 0px 0px; padding: 0px; -webkit-tap-highlight-color: rgba(200, 200, 200, 0); color: #333333; font-family: 微软雅黑, 'Microsoft YaHei'; font-size: 16px;"><img style="color: transparent; font-size: 0px; vertical-align: middle; border: 0px; display: block; width: 910px; max-width: 100%; height: auto; margin-top: 15px; border-radius: 4px;" src="http://img1.lotour.net/Inspiration/2018/0911/20180911092855871455378_910.jpg" alt="" /></p>-->
    <!--<p style="margin: 20px 0px 0px; padding: 0px; -webkit-tap-highlight-color: rgba(200, 200, 200, 0); color: #333333; font-family: 微软雅黑, 'Microsoft YaHei'; font-size: 16px;">影视剧中，我们仅仅关注生前的一瞬繁华，而死后的哀荣却是历史永恒的盖棺定论。居住在紫禁城中的后妃们，能用来陪伴皇帝的余生最多也不过二三十年。不是短命福薄香消玉殒，便是长寿寡恩花容已逝。似乎只有等到百年之后，待一切归于平静，这些后宫之中的女人们才可能有机会与皇帝长眠一处。</p>-->
    <!--<p style="margin: 20px 0px 0px; padding: 0px; -webkit-tap-highlight-color: rgba(200, 200, 200, 0); color: #333333; font-family: 微软雅黑, 'Microsoft YaHei'; font-size: 16px;"><img style="color: transparent; font-size: 0px; vertical-align: middle; border: 0px; display: block; width: 910px; max-width: 100%; height: auto; margin-top: 15px; border-radius: 4px;" src="http://img1.lotour.net/Inspiration/2018/0911/20180911092931211318159_910.jpg" alt="" /></p>-->
    <!--<p style="margin: 20px 0px 0px; padding: 0px; -webkit-tap-highlight-color: rgba(200, 200, 200, 0); color: #333333; font-family: 微软雅黑, 'Microsoft YaHei'; font-size: 16px;"><img style="color: transparent; font-size: 0px; vertical-align: middle; border: 0px; display: block; width: 910px; max-width: 100%; height: auto; margin-top: 15px; border-radius: 4px;" src="http://img1.lotour.net/Inspiration/2018/0911/20180911092852732781163_910.jpg" alt="" /></p>-->
    <!--<p style="margin: 20px 0px 0px; padding: 0px; -webkit-tap-highlight-color: rgba(200, 200, 200, 0); color: #333333; font-family: 微软雅黑, 'Microsoft YaHei'; font-size: 16px;">清东陵的乾隆裕陵里埋葬着乾隆皇帝和《延禧攻略》中的富察皇后、令贵妃、高贵妃，还有另外两位皇贵妃。一座地宫6个人挤在一起，应该算是史上最拥挤的地宫了。想来乾隆皇帝是最喜欢热闹的，从他的&ldquo;农家乐式&rdquo;审美趣味就不难判断出来。即便是百年之后也要惊天动地刷出存在感的。1928年7月，军阀孙殿英觊觎清东陵地宫中的财富，历史上最为明目张胆的盗墓行动开始了。清东陵的地上建筑内，可以移动的财物被洗劫一空，即便是大门上的金门钉和天花板上的金龙和玺彩画也难逃厄运。</p>-->
    <!--<p style="margin: 20px 0px 0px; padding: 0px; -webkit-tap-highlight-color: rgba(200, 200, 200, 0); color: #333333; font-family: 微软雅黑, 'Microsoft YaHei'; font-size: 16px;"><img style="color: transparent; font-size: 0px; vertical-align: middle; border: 0px; display: block; width: 910px; max-width: 100%; height: auto; margin-top: 15px; border-radius: 4px;" src="http://img1.lotour.net/Inspiration/2018/0911/201809110928566887281_910.jpg" alt="" /></p>-->
    <!--<p style="margin: 20px 0px 0px; padding: 0px; -webkit-tap-highlight-color: rgba(200, 200, 200, 0); color: #333333; font-family: 微软雅黑, 'Microsoft YaHei'; font-size: 16px;"><img style="color: transparent; font-size: 0px; vertical-align: middle; border: 0px; display: block; width: 910px; max-width: 100%; height: auto; margin-top: 15px; border-radius: 4px;" src="http://img1.lotour.net/Inspiration/2018/0911/20180911092909751102316_910.jpg" alt="" /></p>-->
    <!--<p style="margin: 20px 0px 0px; padding: 0px; -webkit-tap-highlight-color: rgba(200, 200, 200, 0); color: #333333; font-family: 微软雅黑, 'Microsoft YaHei'; font-size: 16px;"><img style="color: transparent; font-size: 0px; vertical-align: middle; border: 0px; display: block; width: 910px; max-width: 100%; height: auto; margin-top: 15px; border-radius: 4px;" src="http://img1.lotour.net/Inspiration/2018/0911/20180911092924023242214_910.jpg" alt="" /></p>-->
    <!--<p style="margin: 20px 0px 0px; padding: 0px; -webkit-tap-highlight-color: rgba(200, 200, 200, 0); color: #333333; font-family: 微软雅黑, 'Microsoft YaHei'; font-size: 16px;">然而地面上的财富是远远不够满足孙殿英的胃口的，地宫才是清东陵里最大的宝库。裕陵地宫共有4道石门，前3道石门不费吹灰之力就被孙殿英的匪兵打开了。却不曾想地宫尽头通向停放棺椁的最后一道石门，成了最大的障碍。谁也不曾想到，这地宫内的最后一道防线竟然是乾隆皇帝自己。由于裕陵地宫渗水严重，乾隆皇帝的棺椁漂了起来，顶在了最后一道石门之后。</p>-->
    <!--<p style="margin: 20px 0px 0px; padding: 0px; -webkit-tap-highlight-color: rgba(200, 200, 200, 0); color: #333333; font-family: 微软雅黑, 'Microsoft YaHei'; font-size: 16px;"><img style="color: transparent; font-size: 0px; vertical-align: middle; border: 0px; display: block; width: 910px; max-width: 100%; height: auto; margin-top: 15px; border-radius: 4px;" src="http://img1.lotour.net/Inspiration/2018/0911/20180911092927547170556_910.jpg" alt="" /></p>-->
    <!--<p style="margin: 20px 0px 0px; padding: 0px; -webkit-tap-highlight-color: rgba(200, 200, 200, 0); color: #333333; font-family: 微软雅黑, 'Microsoft YaHei'; font-size: 16px;"><img style="color: transparent; font-size: 0px; vertical-align: middle; border: 0px; display: block; width: 910px; max-width: 100%; height: auto; margin-top: 15px; border-radius: 4px;" src="http://img1.lotour.net/Inspiration/2018/0911/20180911092900895551858_910.jpg" alt="" /></p>-->
    <!--<p style="margin: 20px 0px 0px; padding: 0px; -webkit-tap-highlight-color: rgba(200, 200, 200, 0); color: #333333; font-family: 微软雅黑, 'Microsoft YaHei'; font-size: 16px;"><img style="color: transparent; font-size: 0px; vertical-align: middle; border: 0px; display: block; width: 910px; max-width: 100%; height: auto; margin-top: 15px; border-radius: 4px;" src="http://img1.lotour.net/Inspiration/2018/0911/20180911092934493255192_910.jpg" alt="" /></p>-->
    <!--<p style="margin: 20px 0px 0px; padding: 0px; -webkit-tap-highlight-color: rgba(200, 200, 200, 0); color: #333333; font-family: 微软雅黑, 'Microsoft YaHei'; font-size: 16px;">有人说，地宫渗水，棺材漂起来形成水流棺很是正常。但若想令棺椁漂浮起来又谈何容易？而且另外5具棺椁不是完好的停放在棺床上吗？毕竟棺椁与棺床之间有定棺石进行榫卯结构的连接，十分坚固。更何况乾隆皇帝的棺椁还是财宝众多，最为沉重的一个。更奇怪的是，当溥仪组织遗老遗少进入地宫去善后，再次遇见了乾隆皇帝的水流棺。连自家子孙都被乾隆皇帝挡在了外面。一连两次的浮棺之谜，成就了清东陵内一桩至今无解的悬案。或许是乾隆皇帝在天有灵，以一己之身实力护妻吧！没想到被网友吐槽&ldquo;大猪蹄子&rdquo;的乾隆皇帝，死后竟是如此&ldquo;有担当&rdquo;！</p>-->
    <!--<p style="margin: 20px 0px 0px; padding: 0px; -webkit-tap-highlight-color: rgba(200, 200, 200, 0); color: #333333; font-family: 微软雅黑, 'Microsoft YaHei'; font-size: 16px;"><img style="color: transparent; font-size: 0px; vertical-align: middle; border: 0px; display: block; width: 910px; max-width: 100%; height: auto; margin-top: 15px; border-radius: 4px;" src="http://img1.lotour.net/Inspiration/2018/0911/20180911092923223853930_910.jpg" alt="" /></p>-->
    <!--<p style="margin: 20px 0px 0px; padding: 0px; -webkit-tap-highlight-color: rgba(200, 200, 200, 0); color: #333333; font-family: 微软雅黑, 'Microsoft YaHei'; font-size: 16px;"><img style="color: transparent; font-size: 0px; vertical-align: middle; border: 0px; display: block; width: 910px; max-width: 100%; height: auto; margin-top: 15px; border-radius: 4px;" src="http://img1.lotour.net/Inspiration/2018/0911/20180911092931027936480_910.jpg" alt="" /></p>-->
    <!--<p style="margin: 20px 0px 0px; padding: 0px; -webkit-tap-highlight-color: rgba(200, 200, 200, 0); color: #333333; font-family: 微软雅黑, 'Microsoft YaHei'; font-size: 16px;"><img style="color: transparent; font-size: 0px; vertical-align: middle; border: 0px; display: block; width: 910px; max-width: 100%; height: auto; margin-top: 15px; border-radius: 4px;" src="http://img1.lotour.net/Inspiration/2018/0911/20180911092926772945893_910.jpg" alt="" /></p>-->
    <!--<p style="margin: 20px 0px 0px; padding: 0px; -webkit-tap-highlight-color: rgba(200, 200, 200, 0); color: #333333; font-family: 微软雅黑, 'Microsoft YaHei'; font-size: 16px;">但孙殿英的炸药的威力可不是闹着玩儿的。最后一道石门被暴力炸开，压住了乾隆皇帝的朱红色棺椁。据说就连乾隆皇帝的头骨下颚都被炸药震碎了。但他深深的眼眶中依然闪过凌厉的白光，令人不寒而栗。其他的棺椁也严重受损，还不时有白骨漂浮在泥水中难以辨别其主人。但意外的是，孝仪纯皇后（令贵妃）的尸身竟完好的保存了下来。不仅并未腐烂、皮骨具存，而且笑容可掬，宛若古佛。当另外4位后妃尸骨散落无主的时候，令妃娘娘却是如此淡定，果然是在大清后宫的PK中笑到了最后。默默的心疼富察皇后和高贵妃一秒钟。</p>-->
    <!--<h2 style="margin: 35px 0px 18px; padding: 0px 0px 0px 12px; -webkit-tap-highlight-color: rgba(200, 200, 200, 0); font-size: 16px; background-image: url('http://img1.lotour.net/i-article/txt-tit.png'); background-position: 0px center; background-size: initial; background-repeat: no-repeat; background-attachment: initial; background-origin: initial; background-clip: initial; color: #333333; font-family: 微软雅黑, 'Microsoft YaHei';">探秘乾隆皇帝的后宫</h2>-->
    <!--<p style="margin: 20px 0px 0px; padding: 0px; -webkit-tap-highlight-color: rgba(200, 200, 200, 0); color: #333333; font-family: 微软雅黑, 'Microsoft YaHei'; font-size: 16px;"><img style="color: transparent; font-size: 0px; vertical-align: middle; border: 0px; display: block; width: 910px; max-width: 100%; height: auto; margin-top: 15px; border-radius: 4px;" src="http://img1.lotour.net/Inspiration/2018/0911/20180911092937808758298_910.jpg" alt="" /></p>-->
    <!--<p style="margin: 20px 0px 0px; padding: 0px; -webkit-tap-highlight-color: rgba(200, 200, 200, 0); color: #333333; font-family: 微软雅黑, 'Microsoft YaHei'; font-size: 16px;"><img style="color: transparent; font-size: 0px; vertical-align: middle; border: 0px; display: block; width: 910px; max-width: 100%; height: auto; margin-top: 15px; border-radius: 4px;" src="http://img1.lotour.net/Inspiration/2018/0911/20180911092941154380174_910.jpg" alt="" /></p>-->
    <!--<p style="margin: 20px 0px 0px; padding: 0px; -webkit-tap-highlight-color: rgba(200, 200, 200, 0); color: #333333; font-family: 微软雅黑, 'Microsoft YaHei'; font-size: 16px;">而《延禧攻略》中另外几位重要角色又在哪里呢？纯贵妃和继皇后（娴妃）两个正在裕陵妃园寝中作伴呢！《延禧攻略》中被黑化的纯贵妃，在历史上本是一个知书达礼、举止有度的美丽女子。更是为乾隆皇帝诞下两子一女，深得荣宠。而在影视剧中与傅恒的暧昧情缘，纯粹戏剧杜撰。也许是因为其生下的四公主，嫁给了傅恒的儿子福隆安吧！这才被编剧硬生生的扯上了感情线。</p>-->
    <!--<p style="margin: 20px 0px 0px; padding: 0px; -webkit-tap-highlight-color: rgba(200, 200, 200, 0); color: #333333; font-family: 微软雅黑, 'Microsoft YaHei'; font-size: 16px;"><img style="color: transparent; font-size: 0px; vertical-align: middle; border: 0px; display: block; width: 910px; max-width: 100%; height: auto; margin-top: 15px; border-radius: 4px;" src="http://img1.lotour.net/Inspiration/2018/0911/20180911093108066679801_910.jpg" alt="" /></p>-->
    <!--<p style="margin: 20px 0px 0px; padding: 0px; -webkit-tap-highlight-color: rgba(200, 200, 200, 0); color: #333333; font-family: 微软雅黑, 'Microsoft YaHei'; font-size: 16px;"><img style="color: transparent; font-size: 0px; vertical-align: middle; border: 0px; display: block; width: 910px; max-width: 100%; height: auto; margin-top: 15px; border-radius: 4px;" src="http://img1.lotour.net/Inspiration/2018/0911/20180911092944810168972_910.jpg" alt="" /></p>-->
    <!--<p style="margin: 20px 0px 0px; padding: 0px; -webkit-tap-highlight-color: rgba(200, 200, 200, 0); color: #333333; font-family: 微软雅黑, 'Microsoft YaHei'; font-size: 16px;">继皇后辉发那拉氏（娴妃）才是历史上真正被皇帝弃置一旁，死生不复相见的女主角。作为没有被正式废弃的皇后，生前就被收回了一应册宝，打入冷宫，算得上是&ldquo;不废而废&rdquo;了。乾隆皇帝对其怨恨至深超乎了你的想象。在乾隆皇帝即位之初，郎世宁为帝后及嫔妃们绘制的画像中，继皇后的画像被皇帝特意烧毁。即便是帝后嫔妃们在一起的众人画像，有继皇后的部分也被人为进行手动&ldquo;抠图&rdquo;处理，抹掉了她曾经存在的痕迹。</p>-->
    <!--<p style="margin: 20px 0px 0px; padding: 0px; -webkit-tap-highlight-color: rgba(200, 200, 200, 0); color: #333333; font-family: 微软雅黑, 'Microsoft YaHei'; font-size: 16px;"><img style="color: transparent; font-size: 0px; vertical-align: middle; border: 0px; display: block; width: 910px; max-width: 100%; height: auto; margin-top: 15px; border-radius: 4px;" src="http://img1.lotour.net/Inspiration/2018/0911/20180911093000101405982_910.jpg" alt="" /></p>-->
    <!--<p style="margin: 20px 0px 0px; padding: 0px; -webkit-tap-highlight-color: rgba(200, 200, 200, 0); color: #333333; font-family: 微软雅黑, 'Microsoft YaHei'; font-size: 16px;"><img style="color: transparent; font-size: 0px; vertical-align: middle; border: 0px; display: block; width: 910px; max-width: 100%; height: auto; margin-top: 15px; border-radius: 4px;" src="http://img1.lotour.net/Inspiration/2018/0911/20180911093132331327725_910.jpg" alt="" /></p>-->
    <!--<p style="margin: 20px 0px 0px; padding: 0px; -webkit-tap-highlight-color: rgba(200, 200, 200, 0); color: #333333; font-family: 微软雅黑, 'Microsoft YaHei'; font-size: 16px;">也许有人会说，这是乾隆皇帝爱之深恨之切吧！不好意思，还真不是。《延禧攻略》中佘诗曼塑造的娴妃比起《如懿传》里周迅塑造的娴妃来，其处境可能与历史的真实更为相似。继皇后早在宝亲王府潜邸就被立为侧福晋，但直到乾隆十五年被立为皇后，伴君身侧二十年却一直未有子嗣。不得不说，继皇后本身并不得宠。只是乾隆皇帝因遵循太后的意思，按照资历才将其立为皇后的。而从乾隆十七年到乾隆二十年，继皇后先后为乾隆皇帝生下两子一女，也是她成为皇后之后的事情了。乾隆皇帝的无情，令继皇后的身后事操办的颇为草率。虽说要求丧礼依皇贵妃之礼举行，但继皇后真实的待遇甚至还不及一个妃子。同样是皇贵妃，纯贵妃的朱红色棺椁与一旁继后朽烂不堪的棺椁形成了鲜明的对比。</p>-->
    <!--<p style="margin: 20px 0px 0px; padding: 0px; -webkit-tap-highlight-color: rgba(200, 200, 200, 0); color: #333333; font-family: 微软雅黑, 'Microsoft YaHei'; font-size: 16px;"><img style="color: transparent; font-size: 0px; vertical-align: middle; border: 0px; display: block; width: 910px; max-width: 100%; height: auto; margin-top: 15px; border-radius: 4px;" src="http://img1.lotour.net/Inspiration/2018/0911/20180911093113724946414_910.jpg" alt="" /></p>-->
    <!--<p style="margin: 20px 0px 0px; padding: 0px; -webkit-tap-highlight-color: rgba(200, 200, 200, 0); color: #333333; font-family: 微软雅黑, 'Microsoft YaHei'; font-size: 16px;"><img style="color: transparent; font-size: 0px; vertical-align: middle; border: 0px; display: block; width: 910px; max-width: 100%; height: auto; margin-top: 15px; border-radius: 4px;" src="http://img1.lotour.net/Inspiration/2018/0911/20180911093128994183424_910.jpg" alt="" /></p>-->
    <!--<p style="margin: 20px 0px 0px; padding: 0px; -webkit-tap-highlight-color: rgba(200, 200, 200, 0); color: #333333; font-family: 微软雅黑, 'Microsoft YaHei'; font-size: 16px;"><img style="color: transparent; font-size: 0px; vertical-align: middle; border: 0px; display: block; width: 910px; max-width: 100%; height: auto; margin-top: 15px; border-radius: 4px;" src="http://img1.lotour.net/Inspiration/2018/0911/20180911093110429770548_910.jpg" alt="" /></p>-->
    <!--<p style="margin: 20px 0px 0px; padding: 0px; -webkit-tap-highlight-color: rgba(200, 200, 200, 0); color: #333333; font-family: 微软雅黑, 'Microsoft YaHei'; font-size: 16px;">《还珠格格》中最为传奇的香妃娘娘的人物原型，即历史上的容妃和卓氏，也是乾隆皇帝最为宠爱的妃嫔之一。她不仅没有变成蝴蝶飞走了，更是由于她的与众不同，深得太后及后宫嫔妃们的喜爱。也许是有关香妃的传说太多且太过吸引人。裕陵妃园寝内的妃级墓葬，仅有香妃墓对外开放，以供参观。</p>-->
    <!--<p style="margin: 20px 0px 0px; padding: 0px; -webkit-tap-highlight-color: rgba(200, 200, 200, 0); color: #333333; font-family: 微软雅黑, 'Microsoft YaHei'; font-size: 16px;"><img style="color: transparent; font-size: 0px; vertical-align: middle; border: 0px; display: block; width: 910px; max-width: 100%; height: auto; margin-top: 15px; border-radius: 4px;" src="http://img1.lotour.net/Inspiration/2018/0911/2018091109310167736899_910.jpg" alt="" /></p>-->
    <!--<p style="margin: 20px 0px 0px; padding: 0px; -webkit-tap-highlight-color: rgba(200, 200, 200, 0); color: #333333; font-family: 微软雅黑, 'Microsoft YaHei'; font-size: 16px;"><img style="color: transparent; font-size: 0px; vertical-align: middle; border: 0px; display: block; width: 910px; max-width: 100%; height: auto; margin-top: 15px; border-radius: 4px;" src="http://img1.lotour.net/Inspiration/2018/0911/20180911093118373429962_910.jpg" alt="" /></p>-->
    <!--<p style="margin: 20px 0px 0px; padding: 0px; -webkit-tap-highlight-color: rgba(200, 200, 200, 0); color: #333333; font-family: 微软雅黑, 'Microsoft YaHei'; font-size: 16px;">还有抚育过嘉庆皇帝的庆贵妃，生下五阿哥永琪的愉妃，出身于高贵的纳兰家族的舒妃&hellip;&hellip;她们与其它妃嫔及位份极低甚至不知姓名的贵人和常在，一起长眠在这里。喧闹的乾隆后宫终于迎来了永恒的安宁。一茔坟冢，也不过与当时的富贵之家无异。乾隆一朝，共有后宫妃嫔41人。其中36位安葬于裕陵妃园寝之中，永远的延续着在紫禁城中的孤独。而5位获得命运垂怜的女子虽能长伴君侧，也得到了乾隆皇帝生前身后&ldquo;竭尽全力的维护&rdquo;。但不幸的4人仍难逃尸骨散乱难辨的厄运。只有令贵妃穿越生死成为了终极赢家。其实《延禧攻略》到了这一幕，才是真正的大结局</p>-->
    <!--<Divider/>-->
  <!--</div>-->

  <div class="blog-text">
    <h2 style="margin: 26.25pt 0cm 13.5pt;"><span style="font-size: 12pt; line-height: 27.68px; font-family: 微软雅黑, sans-serif; color: #333333;">沙丘边建有&ldquo;沙丘柯南国际机场&rdquo;</span></h2>
    <p style="background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; margin: 15pt 0cm 0.0001pt; -webkit-tap-highlight-color: rgba(200, 200, 200, 0);"><span style="font-family: 微软雅黑, sans-serif; color: #333333;">目前日本鸟取县最出名的东西有两样，鸟取的北荣町是《名侦探柯南》的作者青<span lang="EN-US"><a href="http://www.lotour.com/zhengwen/x3738" target="_blank" rel="noopener"><span lang="EN-US" style="color: #333333;"><span lang="EN-US">山</span></span></a></span>刚昌的故乡，大量的柯南漫画迷，会来这里的&ldquo;青<span lang="EN-US"><a href="http://www.lotour.com/zhengwen/x3738" target="_blank" rel="noopener"><span lang="EN-US" style="color: #333333;"><span lang="EN-US">山</span></span></a></span>刚昌故乡馆&rdquo;<span lang="EN-US"><a href="http://www.lotour.com/zhengwen/x4284" target="_blank" rel="noopener"><span lang="EN-US" style="color: #333333;"><span lang="EN-US">朝圣</span></span></a></span>。而另一个知名的所在，就是鸟取沙丘了，据说每年有超过<span lang="EN-US">200</span>万游客会来鸟取沙丘，就连鸟取沙丘旁原来的&ldquo;鸟取国际机场&rdquo;，现在都改名叫做&ldquo;鸟取沙丘柯南国际机场&rdquo;了，不过由于鸟取县是日本人口最少的都道府县，所以机场的利用率不高，目前只和东京班机通航，还有不定期的海外包机降落柯南机场。</span></p>
    <p style="background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; margin: 15pt 0cm 0.0001pt; -webkit-tap-highlight-color: rgba(200, 200, 200, 0);"><span lang="EN-US" style="font-family: 微软雅黑, sans-serif; color: #333333;"><img src="file:///C:/Users/ASUS/AppData/Local/Temp/msohtmlclip1/01/clip_image001.jpg" alt="http://img1.lotour.net/Inspiration/2018/0829/20180829211153053603185_910.jpg" width="757" height="24" border="0" /></span></p>
    <p class="img-tip" style="background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; margin: 3.75pt 0cm 0.0001pt; line-height: 18pt; -webkit-tap-highlight-color: rgba(200, 200, 200, 0);"><em><span style="font-size: 10.5pt; font-family: 微软雅黑, sans-serif; color: #999999;">图文：钱玮</span></em></p>
    <p style="background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; margin: 15pt 0cm 0.0001pt; -webkit-tap-highlight-color: rgba(200, 200, 200, 0);"><span style="font-family: 微软雅黑, sans-serif; color: #333333;">鸟取沙丘常被宣传称为&ldquo;日本唯一的沙漠&rdquo;，资料说鸟取沙丘东西长约<span lang="EN-US">16</span>公里，南北宽约<span lang="EN-US">2</span>公里，是一个细长的海岸沙丘群。其实鸟取沙丘是由鸟取县的千代川（河流名字）入海口附近的四个海岸沙丘所共同组成，分别是末恒沙丘、湖<span lang="EN-US"><a href="http://www.lotour.com/zhengwen/x3738" target="_blank" rel="noopener"><span lang="EN-US" style="color: #333333;"><span lang="EN-US">山</span></span></a></span>沙丘、浜坂沙丘、福部沙丘，这些从白兔海岸到岩户海岸的沙丘目前统称为鸟取沙丘，所以才有了目前可称为&ldquo;沙漠&rdquo;的规模。</span></p>
    <p style="background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; margin: 15pt 0cm 0.0001pt; -webkit-tap-highlight-color: rgba(200, 200, 200, 0);"><span lang="EN-US" style="font-family: 微软雅黑, sans-serif; color: #333333;"><img src="file:///C:/Users/ASUS/AppData/Local/Temp/msohtmlclip1/01/clip_image002.jpg" alt="http://img1.lotour.net/Inspiration/2018/0904/20180904101335672462738_910.jpg" width="910" height="500" border="0" /></span></p>
    <p class="img-tip" style="background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; margin: 3.75pt 0cm 0.0001pt; line-height: 18pt; -webkit-tap-highlight-color: rgba(200, 200, 200, 0);"><em><span style="font-size: 10.5pt; font-family: 微软雅黑, sans-serif; color: #999999;">翻拍于鸟取沙丘展板照片</span></em></p>
    <p style="background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; margin: 15pt 0cm 0.0001pt; -webkit-tap-highlight-color: rgba(200, 200, 200, 0);"><span style="font-family: 微软雅黑, sans-serif; color: #333333;">游客到访鸟取沙丘，主要前往游览的区域，是鸟取沙丘绿洲周围地区，也就是原来的浜坂沙丘范围，这只是鸟取海岸沙丘其中的一部分，整个鸟取沙丘目前中间各段被河流、<span lang="EN-US"><a href="http://www.lotour.com/zhengwen/x3738" target="_blank" rel="noopener"><span lang="EN-US" style="color: #333333;"><span lang="EN-US">山</span></span></a></span>脉、机场和城镇间隔开。</span></p>
    <p style="background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; margin: 15pt 0cm 0.0001pt; -webkit-tap-highlight-color: rgba(200, 200, 200, 0);"><span lang="EN-US" style="font-family: 微软雅黑, sans-serif; color: #333333;"><img src="file:///C:/Users/ASUS/AppData/Local/Temp/msohtmlclip1/01/clip_image003.jpg" alt="http://img1.lotour.net/Inspiration/2018/0904/20180904102606664877109_910.jpg" width="910" height="526" border="0" /></span></p>
    <p class="img-tip" style="background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; margin: 3.75pt 0cm 0.0001pt; line-height: 18pt; -webkit-tap-highlight-color: rgba(200, 200, 200, 0);"><em><span style="font-size: 10.5pt; font-family: 微软雅黑, sans-serif; color: #999999;">地图影像来自谷歌</span></em></p>
    <p style="background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; margin: 15pt 0cm 0.0001pt; -webkit-tap-highlight-color: rgba(200, 200, 200, 0);"><span style="font-family: 微软雅黑, sans-serif; color: #333333;">两图对比可知，仅仅<span lang="EN-US">60</span>多年，千代川两岸，以及海岸边的鸟取机场周围，大片的原始沙地已被改造，鸟取城镇发展迅速，沙地空间被严重压缩，也只剩下鸟取沙丘绿洲周围地区，以及海岸边沙滩这些沙化区域了。</span></p>
    <p style="background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; margin: 15pt 0cm 0.0001pt; -webkit-tap-highlight-color: rgba(200, 200, 200, 0);"><span lang="EN-US" style="font-family: 微软雅黑, sans-serif; color: #333333;"><img src="file:///C:/Users/ASUS/AppData/Local/Temp/msohtmlclip1/01/clip_image004.jpg" alt="http://img1.lotour.net/Inspiration/2018/0824/20180824232023377789875_910.jpg" width="910" height="511" border="0" /></span></p>
    <p class="img-tip" style="background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; margin: 3.75pt 0cm 0.0001pt; line-height: 18pt; -webkit-tap-highlight-color: rgba(200, 200, 200, 0);"><em><span style="font-size: 10.5pt; font-family: 微软雅黑, sans-serif; color: #999999;">图文：钱玮</span></em></p>
    <p style="background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; margin: 15pt 0cm 0.0001pt; -webkit-tap-highlight-color: rgba(200, 200, 200, 0);"><span style="font-family: 微软雅黑, sans-serif; color: #333333;">由于日本的海洋岛屿地质构造，让它的海岸沙地较为发达，资料称日本大约有<span lang="EN-US">30</span>多个主要的海岸沙滩，所有的大型沙地都分布在海岸线上。其形成原因是波浪的击打和推送，部分沙子被海浪和海风送上岸，产生沙丘堆积。鸟取的大沙丘高度达到<span lang="EN-US">50</span>米，蔚蓝大海前能有如此庞大的沙丘，确实景色蔚为壮观。</span></p>
    <h2 style="margin: 26.25pt 0cm 13.5pt; -webkit-tap-highlight-color: rgba(200, 200, 200, 0);"><span style="font-size: 12pt; line-height: 27.68px; font-family: 微软雅黑, sans-serif; color: #333333;">日本最大的沙丘不在鸟取</span></h2>
    <p style="background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; margin: 15pt 0cm 0.0001pt; -webkit-tap-highlight-color: rgba(200, 200, 200, 0);"><span lang="EN-US" style="font-family: 微软雅黑, sans-serif; color: #333333;"><img src="file:///C:/Users/ASUS/AppData/Local/Temp/msohtmlclip1/01/clip_image005.jpg" alt="http://img1.lotour.net/Inspiration/2018/0904/20180904004801442473243_910.jpg" width="910" height="581" border="0" /></span></p>
    <p class="img-tip" style="background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; margin: 3.75pt 0cm 0.0001pt; line-height: 18pt; -webkit-tap-highlight-color: rgba(200, 200, 200, 0);"><em><span style="font-size: 10.5pt; font-family: 微软雅黑, sans-serif; color: #999999;">地图影像来自谷歌</span></em></p>
    <p style="background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; margin: 15pt 0cm 0.0001pt; -webkit-tap-highlight-color: rgba(200, 200, 200, 0);"><span style="font-family: 微软雅黑, sans-serif; color: #333333;">不过需要特别一说的是，日本最大的沙丘不在鸟取，而是位于青森县的的猿之森沙丘，实际长约<span lang="EN-US">17</span>公里，宽约<span lang="EN-US">1</span>～<span lang="EN-US">2</span>公里，卫星图上初步估算沙地面积是鸟取沙丘面积的<span lang="EN-US">8</span>倍以上，但由于猿之森沙丘周边被用于军事武器测试之用，所以就算是日本人也没有多少人去过那里。对照卫星地图影像比较之后，对于某些国内旅游宣传材料里的&ldquo;日本唯一的沙漠&rdquo;的说法，颇觉得好笑。</span></p>
    <p style="background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; margin: 15pt 0cm 0.0001pt; -webkit-tap-highlight-color: rgba(200, 200, 200, 0);"><span lang="EN-US" style="font-family: 微软雅黑, sans-serif; color: #333333;"><img src="file:///C:/Users/ASUS/AppData/Local/Temp/msohtmlclip1/01/clip_image006.jpg" alt="http://img1.lotour.net/Inspiration/2018/0824/20180824232024327468986_910.jpg" width="910" height="511" border="0" /></span></p>
    <p class="img-tip" style="background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; margin: 3.75pt 0cm 0.0001pt; line-height: 18pt; -webkit-tap-highlight-color: rgba(200, 200, 200, 0);"><em><span style="font-size: 10.5pt; font-family: 微软雅黑, sans-serif; color: #999999;">图文：钱玮</span></em></p>
    <p style="background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; margin: 15pt 0cm 0.0001pt; -webkit-tap-highlight-color: rgba(200, 200, 200, 0);"><span style="font-family: 微软雅黑, sans-serif; color: #333333;">在日本的古代，由于风沙、含盐海风和季风形成的流沙危害，让人们把海岸沙丘地叫做&ldquo;死亡地带&rdquo;。为防御海岸风沙灾害，日本历代都有进行沙地改造，建造过许多造林工程，到目前为止日本绝大多数地区的沙丘、沙地都已经固化，沙丘不再流动，沙丘周边区域被<span lang="EN-US"><a href="http://www.lotour.com/zhengwen/x3725" target="_blank" rel="noopener"><span lang="EN-US" style="color: #333333;"><span lang="EN-US">森林</span></span></a></span>和植被圈围住。</span></p>
    <p style="background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; margin: 15pt 0cm 0.0001pt; -webkit-tap-highlight-color: rgba(200, 200, 200, 0);"><span lang="EN-US" style="font-family: 微软雅黑, sans-serif; color: #333333;"><img src="file:///C:/Users/ASUS/AppData/Local/Temp/msohtmlclip1/01/clip_image007.jpg" alt="http://img1.lotour.net/Inspiration/2018/0824/20180824232028118130716_910.jpg" width="910" height="511" border="0" /></span></p>
    <p class="img-tip" style="background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; margin: 3.75pt 0cm 0.0001pt; line-height: 18pt; -webkit-tap-highlight-color: rgba(200, 200, 200, 0);"><em><span style="font-size: 10.5pt; font-family: 微软雅黑, sans-serif; color: #999999;">图文：钱玮</span></em></p>
    <p style="background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; margin: 15pt 0cm 0.0001pt; -webkit-tap-highlight-color: rgba(200, 200, 200, 0);"><span style="font-family: 微软雅黑, sans-serif; color: #333333;">被圈围和固定住的沙丘，由于日本多数地区降水较多、湿度大，自然环境下<span lang="EN-US">,</span>沙丘水源涵养较好，非常容易表层长草，沙漠上部会逐步被<span lang="EN-US"><a href="http://www.lotour.com/zhengwen/x3743" target="_blank" rel="noopener"><span lang="EN-US" style="color: #333333;"><span lang="EN-US">植物</span></span></a></span>覆盖，渐渐形成泥土层，沙丘面积自然退化减小。</span></p>
    <p style="background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; margin: 15pt 0cm 0.0001pt; -webkit-tap-highlight-color: rgba(200, 200, 200, 0);"><span lang="EN-US" style="font-family: 微软雅黑, sans-serif; color: #333333;"><img src="file:///C:/Users/ASUS/AppData/Local/Temp/msohtmlclip1/01/clip_image008.jpg" alt="http://img1.lotour.net/Inspiration/2018/0829/20180829211149642803380_910.jpg" width="910" height="511" border="0" /></span></p>
    <p class="img-tip" style="background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; margin: 3.75pt 0cm 0.0001pt; line-height: 18pt; -webkit-tap-highlight-color: rgba(200, 200, 200, 0);"><em><span style="font-size: 10.5pt; font-family: 微软雅黑, sans-serif; color: #999999;">图文：钱玮</span></em></p>
    <p style="background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; margin: 15pt 0cm 0.0001pt; -webkit-tap-highlight-color: rgba(200, 200, 200, 0);"><span style="font-family: 微软雅黑, sans-serif; color: #333333;">在鸟取沙丘规模退化的情况下，为了能让更多的游客充分享受海岸沙滩带来的特别感觉，能充分开发当地的海岸沙地特色旅游。<span lang="EN-US">1998</span>年开始，鸟取政府就出资清理了许多邻海沙滩的植被，让连续的沙丘面积增大，这种扩大沙化面积的做法，应该说是世界上很罕见的，也就形成了日本唯一一处可游览参观的&ldquo;海岸沙漠地貌&rdquo;景观。</span></p>
    <h2 style="margin: 26.25pt 0cm 13.5pt; -webkit-tap-highlight-color: rgba(200, 200, 200, 0);"><span style="font-size: 12pt; line-height: 27.68px; font-family: 微软雅黑, sans-serif; color: #333333;">鸟取沙丘的今日面貌</span></h2>
    <p style="background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; margin: 15pt 0cm 0.0001pt; -webkit-tap-highlight-color: rgba(200, 200, 200, 0);"><span lang="EN-US" style="font-family: 微软雅黑, sans-serif; color: #333333;"><img src="file:///C:/Users/ASUS/AppData/Local/Temp/msohtmlclip1/01/clip_image009.jpg" alt="http://img1.lotour.net/Inspiration/2018/0824/20180824232023165231368_910.jpg" width="910" height="607" border="0" /></span></p>
    <p class="img-tip" style="background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; margin: 3.75pt 0cm 0.0001pt; line-height: 18pt; -webkit-tap-highlight-color: rgba(200, 200, 200, 0);"><em><span style="font-size: 10.5pt; font-family: 微软雅黑, sans-serif; color: #999999;">图文：钱玮</span></em></p>
    <p style="background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; margin: 15pt 0cm 0.0001pt; -webkit-tap-highlight-color: rgba(200, 200, 200, 0);"><span style="font-family: 微软雅黑, sans-serif; color: #333333;">鸟取沙丘范围内，现在有相对深达<span lang="EN-US">40</span>米的凹地绿洲<span lang="EN-US"><a href="http://www.lotour.com/zhengwen/x3730" target="_blank" rel="noopener"><span lang="EN-US" style="color: #333333;"><span lang="EN-US">湖泊</span></span></a></span>，也有相对高达<span lang="EN-US">50</span>米的高耸沙丘峰，部分区域还有<span lang="EN-US">5</span>万<span lang="EN-US">5</span>千年前大<span lang="EN-US"><a href="http://www.lotour.com/zhengwen/x3738" target="_blank" rel="noopener"><span lang="EN-US" style="color: #333333;"><span lang="EN-US">山</span></span></a></span>（日本大<span lang="EN-US"><a href="http://www.lotour.com/zhengwen/x3738" target="_blank" rel="noopener"><span lang="EN-US" style="color: #333333;"><span lang="EN-US">山</span></span></a></span>，是鸟取地区最高的老<span lang="EN-US"><a href="http://www.lotour.com/zhengwen/x3742" target="_blank" rel="noopener"><span lang="EN-US" style="color: #333333;"><span lang="EN-US">火山</span></span></a><a href="http://www.lotour.com/zhengwen/x3738" target="_blank" rel="noopener"><span lang="EN-US" style="color: #333333;"><span lang="EN-US">山</span></span></a></span>峰，形象像富士<span lang="EN-US"><a href="http://www.lotour.com/zhengwen/x3738" target="_blank" rel="noopener"><span lang="EN-US" style="color: #333333;"><span lang="EN-US">山</span></span></a></span>，被称为&ldquo;伯耆富士&rdquo;）<span lang="EN-US">,</span>风化<span lang="EN-US"><a href="http://www.lotour.com/zhengwen/x3742" target="_blank" rel="noopener"><span lang="EN-US" style="color: #333333;"><span lang="EN-US">火山</span></span></a></span>灰露出地面的地质景观。</span></p>
    <p style="background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; margin: 15pt 0cm 0.0001pt; -webkit-tap-highlight-color: rgba(200, 200, 200, 0);"><span lang="EN-US" style="font-family: 微软雅黑, sans-serif; color: #333333;"><img src="file:///C:/Users/ASUS/AppData/Local/Temp/msohtmlclip1/01/clip_image010.jpg" alt="http://img1.lotour.net/Inspiration/2018/0824/2018082423202723953417_910.jpg" width="910" height="511" border="0" /></span></p>
    <p class="img-tip" style="background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; margin: 3.75pt 0cm 0.0001pt; line-height: 18pt; -webkit-tap-highlight-color: rgba(200, 200, 200, 0);"><em><span style="font-size: 10.5pt; font-family: 微软雅黑, sans-serif; color: #999999;">图文：钱玮</span></em></p>
    <p style="background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; margin: 15pt 0cm 0.0001pt; -webkit-tap-highlight-color: rgba(200, 200, 200, 0);"><span style="font-family: 微软雅黑, sans-serif; color: #333333;">千代川等河流运送来的<span lang="EN-US"><a href="http://www.lotour.com/zhengwen/x3742" target="_blank" rel="noopener"><span lang="EN-US" style="color: #333333;"><span lang="EN-US">火山</span></span></a></span>灰，因为特殊环境而在入海口周围堆积，硬化后形成高坡，推高了这里的地形，再加上日本海的风吹浪击，历经几万年，就形成了鸟取地区沙丘的特殊地貌。</span></p>
    <p style="background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; margin: 15pt 0cm 0.0001pt; -webkit-tap-highlight-color: rgba(200, 200, 200, 0);"><span lang="EN-US" style="font-family: 微软雅黑, sans-serif; color: #333333;"><img src="file:///C:/Users/ASUS/AppData/Local/Temp/msohtmlclip1/01/clip_image011.jpg" alt="http://img1.lotour.net/Inspiration/2018/0829/20180829211139978264546_910.jpg" width="910" height="607" border="0" /></span></p>
    <p class="img-tip" style="background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; margin: 3.75pt 0cm 0.0001pt; line-height: 18pt; -webkit-tap-highlight-color: rgba(200, 200, 200, 0);"><em><span style="font-size: 10.5pt; font-family: 微软雅黑, sans-serif; color: #999999;">图文：钱玮</span></em></p>
    <p style="background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; margin: 15pt 0cm 0.0001pt; -webkit-tap-highlight-color: rgba(200, 200, 200, 0);"><span style="font-family: 微软雅黑, sans-serif; color: #333333;">高大沙丘靠海的一面，有被强风吹出的人称&ldquo;风纹&rdquo;的图案，也有从沙丘表面如雪崩般滑落下来的沙帘，围着鸟取沙丘小走一圈，起码需要一个小时，整个沙丘区域<span lang="EN-US"><a href="http://www.lotour.com/zhengwen/x3751" target="_blank" rel="noopener"><span lang="EN-US" style="color: #333333;"><span lang="EN-US">徒步</span></span></a></span>游览是免费的，也可以乘坐收费的马车、骆驼等交通工具。</span></p>
    <p style="background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; margin: 15pt 0cm 0.0001pt; -webkit-tap-highlight-color: rgba(200, 200, 200, 0);"><span lang="EN-US" style="font-family: 微软雅黑, sans-serif; color: #333333;"><img src="file:///C:/Users/ASUS/AppData/Local/Temp/msohtmlclip1/01/clip_image012.jpg" alt="http://img.lotour.net/zip/20110411/index_mrtu.jpg" width="6" height="6" border="0" /></span></p>
    <p class="img-tip" style="background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; margin: 3.75pt 0cm 0.0001pt; line-height: 18pt; -webkit-tap-highlight-color: rgba(200, 200, 200, 0);"><em><span style="font-size: 10.5pt; font-family: 微软雅黑, sans-serif; color: #999999;">图文：钱玮</span></em></p>
    <p style="background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; margin: 15pt 0cm 0.0001pt; -webkit-tap-highlight-color: rgba(200, 200, 200, 0);"><span style="font-family: 微软雅黑, sans-serif; color: #333333;">沙丘高地周边还有各种游乐活动，比如乘坐<span lang="EN-US"><a href="http://www.lotour.com/zhengwen/x4148" target="_blank" rel="noopener"><span lang="EN-US" style="color: #333333;"><span lang="EN-US">滑翔伞</span></span></a></span>、滑板滑沙等，还有一个沙漠<span lang="EN-US"><a href="http://www.lotour.com/zhengwen/x4142" target="_blank" rel="noopener"><span lang="EN-US" style="color: #333333;"><span lang="EN-US">露营</span></span></a></span>区，确实很有沙漠游玩的感觉。</span></p>
    <p style="background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; margin: 15pt 0cm 0.0001pt; -webkit-tap-highlight-color: rgba(200, 200, 200, 0);"><span lang="EN-US" style="font-family: 微软雅黑, sans-serif; color: #333333;"><img src="file:///C:/Users/ASUS/AppData/Local/Temp/msohtmlclip1/01/clip_image013.jpg" alt="http://img1.lotour.net/Inspiration/2018/0829/20180829211153749345755_910.jpg" width="910" height="608" border="0" /></span></p>
    <p class="img-tip" style="background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; margin: 3.75pt 0cm 0.0001pt; line-height: 18pt; -webkit-tap-highlight-color: rgba(200, 200, 200, 0);"><em><span style="font-size: 10.5pt; font-family: 微软雅黑, sans-serif; color: #999999;">图片来自<span lang="EN-US"><a href="http://www.lotour.com/zhengwen/x3738" target="_blank" rel="noopener"><span lang="EN-US" style="color: #999999;"><span lang="EN-US">山</span></span></a></span>阴观光推进机构</span></em></p>
    <p style="background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; margin: 15pt 0cm 0.0001pt; -webkit-tap-highlight-color: rgba(200, 200, 200, 0);"><span style="font-family: 微软雅黑, sans-serif; color: #333333;">在沙丘附近，还有一座室内的沙雕<span lang="EN-US"><a href="http://www.lotour.com/zhengwen/x3712" target="_blank" rel="noopener"><span lang="EN-US" style="color: #333333;"><span lang="EN-US">博物馆</span></span></a></span>，里面有很壮观的沙雕作品，展现世界各地不同的建筑和风土人情，沙雕<span lang="EN-US"><a href="http://www.lotour.com/zhengwen/x3712" target="_blank" rel="noopener"><span lang="EN-US" style="color: #333333;"><span lang="EN-US">博物馆</span></span></a></span>里的作品会定期更新，所以每次去可能看到的沙雕作品都会有不同。</span></p>
    <p style="background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; margin: 15pt 0cm 0.0001pt; -webkit-tap-highlight-color: rgba(200, 200, 200, 0);"><span lang="EN-US" style="font-family: 微软雅黑, sans-serif; color: #333333;"><img src="file:///C:/Users/ASUS/AppData/Local/Temp/msohtmlclip1/01/clip_image012.jpg" alt="http://img.lotour.net/zip/20110411/index_mrtu.jpg" width="6" height="6" border="0" /></span></p>
    <p class="img-tip" style="background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; margin: 3.75pt 0cm 0.0001pt; line-height: 18pt; -webkit-tap-highlight-color: rgba(200, 200, 200, 0);"><em><span style="font-size: 10.5pt; font-family: 微软雅黑, sans-serif; color: #999999;">图片来自<span lang="EN-US"><a href="http://www.lotour.com/zhengwen/x3738" target="_blank" rel="noopener"><span lang="EN-US" style="color: #999999;"><span lang="EN-US">山</span></span></a></span>阴观光推进机构</span></em></p>
    <h2 style="margin: 26.25pt 0cm 13.5pt; -webkit-tap-highlight-color: rgba(200, 200, 200, 0);"><span style="font-size: 12pt; line-height: 27.68px; font-family: 微软雅黑, sans-serif; color: #333333;">鸟取沙丘和<span lang="EN-US"><a href="http://www.lotour.com/zhengwen/x3738" target="_blank" rel="noopener"><span lang="EN-US" style="color: #333333;"><span lang="EN-US">山</span></span></a></span>阴海岸国立公园</span></h2>
    <p style="background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; margin: 15pt 0cm 0.0001pt; -webkit-tap-highlight-color: rgba(200, 200, 200, 0);"><span style="font-family: 微软雅黑, sans-serif; color: #333333;">鸟取沙丘其实只是日本<span lang="EN-US"><a href="http://www.lotour.com/zhengwen/x3738" target="_blank" rel="noopener"><span lang="EN-US" style="color: #333333;"><span lang="EN-US">山</span></span></a></span>阴海岸国立公园的一部分，<span lang="EN-US">2010</span>年<span lang="EN-US">10</span>月<span lang="EN-US"><a href="http://www.lotour.com/zhengwen/x3738" target="_blank" rel="noopener"><span lang="EN-US" style="color: #333333;"><span lang="EN-US">山</span></span></a></span>阴海岸国立公园被联合国教科文组织认定为世界地质公园。<span lang="EN-US"><a href="http://www.lotour.com/zhengwen/x3738" target="_blank" rel="noopener"><span lang="EN-US" style="color: #333333;"><span lang="EN-US">山</span></span></a></span>阴海岸国立公园西起鸟取市，东至京都府京丹后市，长约<span lang="EN-US">110</span>公里，公园保存了地壳变动和<span lang="EN-US"><a href="http://www.lotour.com/zhengwen/x3742" target="_blank" rel="noopener"><span lang="EN-US" style="color: #333333;"><span lang="EN-US">火山</span></span></a></span>活动的大量痕迹，从中可以了解日本海形成至今的地形变迁和沙丘、沉降海岸等多种海岸地形，被誉为&ldquo;地形和地质<span lang="EN-US"><a href="http://www.lotour.com/zhengwen/x3712" target="_blank" rel="noopener"><span lang="EN-US" style="color: #333333;"><span lang="EN-US">博物馆</span></span></a></span>&rdquo;。</span></p>
    <p style="background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; margin: 15pt 0cm 0.0001pt; -webkit-tap-highlight-color: rgba(200, 200, 200, 0);"><span lang="EN-US" style="font-family: 微软雅黑, sans-serif; color: #333333;"><img src="file:///C:/Users/ASUS/AppData/Local/Temp/msohtmlclip1/01/clip_image012.jpg" alt="http://img.lotour.net/zip/20110411/index_mrtu.jpg" width="6" height="6" border="0" /></span></p>
    <p class="img-tip" style="background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; margin: 3.75pt 0cm 0.0001pt; line-height: 18pt; -webkit-tap-highlight-color: rgba(200, 200, 200, 0);"><em><span style="font-size: 10.5pt; font-family: 微软雅黑, sans-serif; color: #999999;">图文：钱玮</span></em></p>
    <p style="background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; margin: 15pt 0cm 0.0001pt; -webkit-tap-highlight-color: rgba(200, 200, 200, 0);"><span style="font-family: 微软雅黑, sans-serif; color: #333333;">在鸟取沙丘旁边，有景色奇特的浦富海岸景观，浦富海岸是日本国家名胜、天然纪念物，同时还被选为&ldquo;日本百景&rdquo;、&ldquo;日本白砂青松百选&rdquo;、&ldquo;日本海滨百选&rdquo;、&ldquo;平成日本观光地百选&rdquo;之一，是日本海沿岸的自然名胜。</span></p>
    <p style="background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; margin: 15pt 0cm 0.0001pt; -webkit-tap-highlight-color: rgba(200, 200, 200, 0);"><span lang="EN-US" style="font-family: 微软雅黑, sans-serif; color: #333333;"><img src="file:///C:/Users/ASUS/AppData/Local/Temp/msohtmlclip1/01/clip_image014.jpg" alt="http://img1.lotour.net/Inspiration/2018/0829/20180829211153437317746_910.jpg" width="910" height="511" border="0" /></span></p>
    <p class="img-tip" style="background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; margin: 3.75pt 0cm 0.0001pt; line-height: 18pt; -webkit-tap-highlight-color: rgba(200, 200, 200, 0);"><em><span style="font-size: 10.5pt; font-family: 微软雅黑, sans-serif; color: #999999;">图片来自<span lang="EN-US"><a href="http://www.lotour.com/zhengwen/x3738" target="_blank" rel="noopener"><span lang="EN-US" style="color: #999999;"><span lang="EN-US">山</span></span></a></span>阴观光推进机构</span></em></p>
    <p style="background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; margin: 15pt 0cm 0.0001pt; -webkit-tap-highlight-color: rgba(200, 200, 200, 0);"><span style="font-family: 微软雅黑, sans-serif; color: #333333;">很多来鸟取沙丘的游客都错过来了这个<span lang="EN-US"><a href="http://www.lotour.com/zhengwen/x3783" target="_blank" rel="noopener"><span lang="EN-US" style="color: #333333;"><span lang="EN-US">摄影</span></span></a></span>绝佳的地方。浦富海岸位于鸟取岩美郡的岩美町，是一段长约<span lang="EN-US">15</span>公里的里阿斯式海岸，沿岸共有<span lang="EN-US">166</span>个岛屿、<span lang="EN-US">16</span>个洞门、<span lang="EN-US">6</span>个洞窟等。里阿斯式海岸是一种因为土地沉降和海水上升而形成的宛如锯齿般的复杂海岸形态。</span></p>
    <p style="background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; margin: 15pt 0cm 0.0001pt; -webkit-tap-highlight-color: rgba(200, 200, 200, 0);"><span lang="EN-US" style="font-family: 微软雅黑, sans-serif; color: #333333;"><img src="file:///C:/Users/ASUS/AppData/Local/Temp/msohtmlclip1/01/clip_image015.jpg" alt="http://img1.lotour.net/Inspiration/2018/0829/20180829211154168255502_910.jpg" width="910" height="606" border="0" /></span></p>
    <p class="img-tip" style="background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; margin: 3.75pt 0cm 0.0001pt; line-height: 18pt; -webkit-tap-highlight-color: rgba(200, 200, 200, 0);"><em><span style="font-size: 10.5pt; font-family: 微软雅黑, sans-serif; color: #999999;">图片来自<span lang="EN-US"><a href="http://www.lotour.com/zhengwen/x3738" target="_blank" rel="noopener"><span lang="EN-US" style="color: #999999;"><span lang="EN-US">山</span></span></a></span>阴观光推进机构</span></em></p>
    <p style="background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; margin: 15pt 0cm 0.0001pt; -webkit-tap-highlight-color: rgba(200, 200, 200, 0);"><span style="font-family: 微软雅黑, sans-serif; color: #333333;">浦富海岸边形成了花岗岩断崖、奇岩、洞窟等地形，海面上散布着大大小小的岛屿和岩石，由于与&ldquo;日本三景&rdquo;之一的宫城县松岛很相似，所以被称为&ldquo;<span lang="EN-US"><a href="http://www.lotour.com/zhengwen/x3738" target="_blank" rel="noopener"><span lang="EN-US" style="color: #333333;"><span lang="EN-US">山</span></span></a></span>阴松岛&rdquo;。各类景点中，以&ldquo;千贯松岛&rdquo;最为有名，这是一座三角形的中空巨岩，岩上生有松树。据说在江户时代，乘船游览浦富海岸的鸟取藩第二代藩主池田纲清说：&ldquo;谁要是能将这座长有松树的岩石搬到我的庭园里，就赏给他<span lang="EN-US">1000</span>贯钱&rdquo;，&ldquo;千贯松岛&rdquo;的名字即由此而来。</span></p>
    <p style="background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; margin: 15pt 0cm 0.0001pt; -webkit-tap-highlight-color: rgba(200, 200, 200, 0);"><span lang="EN-US" style="font-family: 微软雅黑, sans-serif; color: #333333;"><img src="file:///C:/Users/ASUS/AppData/Local/Temp/msohtmlclip1/01/clip_image016.jpg" alt="http://img1.lotour.net/Inspiration/2018/0829/20180829211152633467196_910.jpg" width="910" height="593" border="0" /></span></p>
    <p class="img-tip" style="background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; margin: 3.75pt 0cm 0.0001pt; line-height: 18pt; -webkit-tap-highlight-color: rgba(200, 200, 200, 0);"><em><span style="font-size: 10.5pt; font-family: 微软雅黑, sans-serif; color: #999999;">图片来自<span lang="EN-US"><a href="http://www.lotour.com/zhengwen/x3738" target="_blank" rel="noopener"><span lang="EN-US" style="color: #999999;"><span lang="EN-US">山</span></span></a></span>阴观光推进机构</span></em></p>
    <p style="background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; margin: 15pt 0cm 0.0001pt; -webkit-tap-highlight-color: rgba(200, 200, 200, 0);"><span style="font-family: 微软雅黑, sans-serif; color: #333333;">了解更多奇特旅行资讯和美图，请关注我的新浪微博：金蛋<span lang="EN-US">_</span>知行合一。拍摄、约稿、合作，请联系微信：<span lang="EN-US">qian_0_wei</span></span></p>
    <p><span style="font-family: 微软雅黑, sans-serif; color: #333333;"><span lang="EN-US">&nbsp;</span></span></p>
  </div>
</template>

<script>
  import $ from "jquery";

  export default {
    name: "blog",
    mounted(){
      var imgArr = $(".blog-text img");

      for(var i = 0;i < imgArr.length;i++){
        if(imgArr[i].alt.length != 0 && imgArr[i].alt.indexOf("http://") >= 0){
          imgArr[i].src = imgArr[i].alt;
        }

      }
    }

  }
</script>

<style scoped>
  .blog-text {
    float: right;
    display: inline-block;
    min-height: 600px;
  }

  img {
    width: 100%;
    border-radius: 4px;
  }

  p {
    margin: 20px 0 0;
    font: normal 16px/28px \5FAE\8F6F\96C5\9ED1, "Microsoft YaHei";
    color: #333;
    text-align: left;
  }

  /*图片描述语言*/
  p.img-tip {
    position: relative;
    font-size: 14px;
    font-style: italic;
    line-height: 20px;
    color: #999;
    margin-top: 5px;
    text-align: left;
  }

  h2 {
    margin: 35px 0 18px;
    padding-left: 12px;
    background: url(http://img1.lotour.net/i-article/txt-tit.png) no-repeat 0 center;
    font-weight: bold;
  }
</style>
